version: 2

registries:
  gitlab-pypi:
    type: python-index
    url: https://gitlab.com/api/v4/projects/30941368/packages/pypi/simple
    username: ${{ secrets.GITLAB_PYPI_SECRET_NAME }}
    password: ${{ secrets.GITLAB_PYPI_SECRET }}

updates:
  - package-ecosystem: "pip"
    directory: "/"
    insecure-external-code-execution: allow
    registries:
      - gitlab-pypi
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
