repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.0.0"
    hooks:
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: "21.8b0"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: "5.9.2"
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        files: ^src/
        entry: poetry run mypy
        language: system
        types: [python]
