version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    tty: true
    networks:
      - local

  database:
    image: postgres:13.4

networks:
  local:
    driver: bridge
