FROM renovate/renovate:slim

USER root

ENV RENOVATE_BINARY_SOURCE=global

# renovate: datasource=docker depName=python versioning=docker
ENV PYTHON_VERSION=3.9.6

# renovate: datasource=pypi depName=poetry
ENV POETRY_VERSION=1.1.11

RUN install-tool python ${PYTHON_VERSION}
RUN install-tool poetry ${POETRY_VERSION}

USER 1000
