name: CI

on:
  workflow_dispatch:

jobs:
  foo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.6" # renovate: datasource=docker depName=python versioning=docker

  bar:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.6" # renovate: datasource=docker depName=python versioning=docker
      - name: Install Poetry
        uses: snok/install-poetry@v1.2.0
        with:
          version: "1.1.10" # renovate: datasource=pypi depName=poetry
          virtualenvs-in-project: true
