name: Update dependencies using Renovate Docker slim image

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "info"

jobs:
  renovate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Generate GitHub app token
        id: generate_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_PEM }}
      - name: Ensure that `docker.sock` is accessible to Docker containers
        run: sudo chown 1000:docker /var/run/docker.sock
      - name: Run Renovate
        run: >
          docker run --rm
          -e RENOVATE_TOKEN="x-access-token:${{ steps.generate_token.outputs.token }}"
          -e GITLAB_PYPI_SECRET_NAME=${{ secrets.GITLAB_PYPI_SECRET_NAME }}
          -e GITLAB_PYPI_SECRET=${{ secrets.GITLAB_PYPI_SECRET }}
          -e LOG_LEVEL=${{ github.event.inputs.logLevel }}
          -v ${{ github.workspace }}/.renovate/config.js:/usr/src/app/config.js
          -v /var/run/docker.sock:/var/run/docker.sock
          -v /tmp:/tmp
          renovate/renovate:slim
